#!/bin/sh /etc/rc.common

START=15
STOP=01
USE_PROCD=1

NAME=fancontrol
PROG=/usr/bin/$NAME

start_service() {
    config_load "$NAME"

    local enable
    config_get enable settings enable
    [ "$enable" = "1" ] || { echo "Instance \"$NAME\" disabled."; return 1; }

    local mode
    config_get mode settings mode

    procd_open_instance
    procd_set_param command $PROG
    [ -n "$mode" ] && procd_append_param command -M "$mode"
    procd_set_param respawn
    procd_close_instance
}

start() {
    start_service
}

stop() {
    procd_kill_instance
}

reload() {
    procd_reload_instance
}

service_triggers() {
    procd_add_reload_trigger "fancontrol"
}
