#!/bin/sh
case "$ACTION" in
  ifup|ifupdate|ifdown)
     case "$INTERFACE" in
       lan|USB|USBv6|wan6) [ -x /usr/bin/ipv6-guard.sh ] && /usr/bin/ipv6-guard.sh >/dev/null 2>&1 & ;;
     esac
     ;;
esac
exit 0
