#!/bin/sh
# Trigger OpenClash WAN DNS sync on QMI WAN ifup/ifupdate or DNS change
case "$ACTION" in
  ifup|ifupdate|ifdown)
     case "$INTERFACE" in
       USB|USBv6|wan|wan6)
          [ -x /usr/bin/oc-wandns.sh ] && /usr/bin/oc-wandns.sh >/dev/null 2>&1 &
          ;;
     esac
     ;;
esac
exit 0
